### ISSUE TITLE
What's `LibCore.py`?

### ISSUE THREAD

**Issue by fu050409** [HydroRoll-Team/HydroRollCore#6]
Hi! It seems https://github.com/HydroRoll-Team/HydroRollCore/blob/main/hrc/LibCore.py is not a valid python script, perhaps this file is a binary library? If so, I think you can just remove this file from github repository and build it when you're developing on your local machine or during ci.

**Comment by HsiangNianian** [comment]
literally and indeed, you can create a PR to put libcore into gitignore :D
